### ISSUE TITLE
Application beyond described use

### ISSUE THREAD

**Issue by Kcjohnson** [marcjwilliams1/neutralitytestr#1]
@marcjwilliams1 First off, thanks for making this resource available as a companion to your paper, very helpful. The suggested neutralitytestr approach seems to be including read-depth, cellularity,  and all mutations in diploid regions. We've implemented this approach with a cohort of tumor samples for which we have both primary and matched-recurrent tumor sequencing data across a few molecular-subtypes. It was easy to use and works well.

I am interested in extending this method beyond its standard use in the two scenarios described below. However, I am not sure whether these applications are entirely appropriate and I was hoping you might be able to offer any guidance. 

1) Testing whether mutations that are present ONLY in the recurrent or primary tumor follow a pattern consistent (or not) with neutral evolution. I would apply the function to a VAF vector subsetted to only include those newly acquired or shed mutations. In some cases, this can greatly reduce the number of mutations considered in the model. Broadly, I wasn't sure whether this was an acceptable approach and specifically I wasn't sure whether there was a suggested minimum number of mutations to work with?

2) Is it possible to merge the VAF vectors at the level of tumor subtype and run the algorithm? That is, apply the algorithm multiple samples instead of a single-sample (e.g., all mutations specific to the primary tumor of tumor subtype A). Mutation rates are similar within tumor subtype, but I wasn't sure  whether concatenating multiple samples would violate the model's assumptions. 

Thanks,
Kevin

**Comment by marcjwilliams1** [comment]
Hi @Kcjohnson, thanks for trying out the package, glad its proved useful. Just catching up stuff after the holidays so sorry for taking a while to get back to you.

1) In theory, this should work but yes it gets difficult if you have a limited number of mutations. In the paper we recommended a minimum of 12 subclonal mutations, while this is supported well by simulations these are of course idealized. By now I'd probably recommend 30+ mutations. On a side note, perhaps what would be more interesting in this case and something I'm sure you're thinking about is to look at what mutations are shared between samples and their clonality in the samples. At the moment neutralitytestr is limited in scope to just subclonal mutations in single samples, we're thinking about how to extend this to multiregion data and timeseries data at the moment. I'll let you know when/if neutralitytestr gets extended for this in case it's of use.

2) It's certainly possible, and something I've played around with a bit. There are a few caveats though. You should make sure to correct for the cellularity/purity, so that you can merge the samples correctly. Secondly the mutation rate estimates won't mean much in this case, but looking at the merged VAF distributions can allow you to see if the patterns are consistent with the neutral model across the cohort. You should also be aware that any tumours that individually may not fit the model could be masked when merging. For example if you had 1/20 samples that looked non-neutral, when merging what you would probably find is that the neutral model fits well at the cohort level.

Hope that helps!

**Comment by Kcjohnson** [comment]
@marcjwilliams1, thanks for the detailed reply. I'll be sure to incorporate your suggestions as I move forward with these analyses.
